
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='TrafficToll',
    version='1.5.0',
    description='NetLimiter-like bandwidth limiting and QoS for Linux',
    python_requires='==3.*,>=3.6.0',
    project_urls={"homepage": "https://github.com/cryzed/TrafficToll", "repository": "https://github.com/cryzed/TrafficToll"},
    author='Chris Braun',
    author_email='cryzed@googlemail.com',
    license='GPLv3',
    keywords='traffic traffic control traffic shaping tc netlimiter qos',
    entry_points={"console_scripts": ["tt = traffictoll.__main__:main"]},
    packages=['traffictoll'],
    package_dir={"": "."},
    package_data={},
    install_requires=['psutil==5.*,>=5.6.7', 'ruamel.yaml==0.*,>=0.16.6'],
    extras_require={"dev": ["black==19.*,>=19.10.0.b0", "mypy==0.*,>=0.761.0"]},
)
